const STUDENTS_DATA = {
  "weekLabel": "الأسبوع الأول",
  "lastUpdated": "15 يونيو 2025",
  "students": [
    {
      "id": 1,
      "name": "إياس",
      "totalPoints": 40,
      "weekPoints": 40,
      "attendance": 3,
      "absences": 0,
      "absencesExcused": 0,
      "dresscode": 2,
      "pagesMemorized": 2,
      "review": 1,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": "تسميع صفحة + مراجعة"
    },
    {
      "id": 2,
      "name": "كرم المصري",
      "totalPoints": 10,
      "weekPoints": 10,
      "attendance": 1,
      "absences": 0,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 1,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": "تسميع صفحة"
    },
    {
      "id": 3,
      "name": "عمر",
      "totalPoints": 5,
      "weekPoints": 5,
      "attendance": 1,
      "absences": 0,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": ""
    },
    {
      "id": 4,
      "name": "جود",
      "totalPoints": 5,
      "weekPoints": 5,
      "attendance": 1,
      "absences": 0,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": ""
    },
    {
      "id": 5,
      "name": "عبد الملك",
      "totalPoints": 5,
      "weekPoints": 5,
      "attendance": 1,
      "absences": 0,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": ""
    },
    {
      "id": 6,
      "name": "ليث",
      "totalPoints": 5,
      "weekPoints": 5,
      "attendance": 1,
      "absences": 0,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": ""
    },
    {
      "id": 7,
      "name": "كرم العليا",
      "totalPoints": 0,
      "weekPoints": -20,
      "attendance": 0,
      "absences": 1,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": "غياب (أول مرة)"
    },
    {
      "id": 8,
      "name": "مالك",
      "totalPoints": 0,
      "weekPoints": -20,
      "attendance": 0,
      "absences": 1,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": "غياب (أول مرة)"
    },
    {
      "id": 9,
      "name": "أغيد",
      "totalPoints": 0,
      "weekPoints": -20,
      "attendance": 0,
      "absences": 1,
      "absencesExcused": 0,
      "dresscode": 0,
      "pagesMemorized": 0,
      "review": 0,
      "forgotCard": 0,
      "istighfar": 0,
      "completedJuz": 0,
      "bonusPoints": 0,
      "bonusReason": "",
      "details": "غياب (أول مرة)"
    }
  ]
};
